/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nomina_hospital_san_marcos.vista;

import com.nomina_hospital_san_marcos.controlador.ControladorNomina;
import com.nomina_hospital_san_marcos.controlador.ControladorUsuario;
import com.nomina_hospital_san_marcos.modelo.TecSistemas;
import com.nomina_hospital_san_marcos.modelo.Trabajador;
import com.nomina_hospital_san_marcos.modelo.Usuario;
import java.beans.PropertyVetoException;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.synth.SynthOptionPaneUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class MDIINomina extends javax.swing.JFrame {

     private ControladorUsuario controlUsuarios;
     private ControladorNomina controlNomina;
     
   
    /**
     * Creates new form MDIINomina
     */
    public MDIINomina() {
        initComponents();
        controlarEstadoInicio(false);
        controlUsuarios = new ControladorUsuario();
        controlNomina  = new ControladorNomina();
        txtCorreo.setText("idgomez90447@umanizales.edu.co");
        txtContraseña.setText("123456");
        llenarTrabajadores();
        
    }
    private void llenarTrabajadores()
    {
        DefaultTableModel model = (DefaultTableModel) TBLTrabajadores.getModel();
        model.getDataVector().removeAllElements();
        //Object[] fila = {"3546584", "Ivan Gomez", "3000000", false};
        
        //model.addRow(fila);
        for(Trabajador trab: controlNomina.getTrabadores())
        {
            if(trab!=null)
            {
            Object[] fila= {trab.getCedula(), trab.getNombre(), trab.getSalario(), trab.isLicencia()};
            model.addRow(fila);
            }
        }

        TBLTrabajadores.repaint();
                
    }
    
    public void controlarEstadoInicio(boolean estado)
    {
        
        
         InoListarTrabadores.setEnabled(estado);
         InoCrearTrabajador.setEnabled(estado);
         InoCalcularNomina.setEnabled(estado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        JIFRegistrarTrabajador = new javax.swing.JInternalFrame();
        TXTCrearTrabajador = new javax.swing.JTextField();
        tbRegistrar = new javax.swing.JToggleButton();
        JIFLogin = new javax.swing.JInternalFrame();
        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        JIFListarEmpleados = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLTrabajadores = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        InoListarTrabadores = new javax.swing.JMenuItem();
        InoCrearTrabajador = new javax.swing.JMenuItem();
        InoCalcularNomina = new javax.swing.JMenuItem();
        InoSalir = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JIFRegistrarTrabajador.setClosable(true);
        JIFRegistrarTrabajador.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        JIFRegistrarTrabajador.setIconifiable(true);
        JIFRegistrarTrabajador.setMaximizable(true);
        JIFRegistrarTrabajador.setResizable(true);
        JIFRegistrarTrabajador.setTitle("Registro Trabajador");
        JIFRegistrarTrabajador.setVisible(false);

        TXTCrearTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCrearTrabajadorActionPerformed(evt);
            }
        });

        tbRegistrar.setText("Registrar");
        tbRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JIFRegistrarTrabajadorLayout = new javax.swing.GroupLayout(JIFRegistrarTrabajador.getContentPane());
        JIFRegistrarTrabajador.getContentPane().setLayout(JIFRegistrarTrabajadorLayout);
        JIFRegistrarTrabajadorLayout.setHorizontalGroup(
            JIFRegistrarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFRegistrarTrabajadorLayout.createSequentialGroup()
                .addGroup(JIFRegistrarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JIFRegistrarTrabajadorLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(TXTCrearTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JIFRegistrarTrabajadorLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(tbRegistrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JIFRegistrarTrabajadorLayout.setVerticalGroup(
            JIFRegistrarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFRegistrarTrabajadorLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(TXTCrearTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(tbRegistrar)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        desktopPane.add(JIFRegistrarTrabajador);
        JIFRegistrarTrabajador.setBounds(330, 90, 210, 230);

        JIFLogin.setClosable(true);
        JIFLogin.setIconifiable(true);
        JIFLogin.setMaximizable(true);
        JIFLogin.setResizable(true);
        JIFLogin.setTitle("Ingreso a Calculo Nomina");
        JIFLogin.setVisible(true);

        lblUsuario.setText("*Correo:");

        lblContraseña.setText("*Contraseña:");

        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JIFLoginLayout = new javax.swing.GroupLayout(JIFLogin.getContentPane());
        JIFLogin.getContentPane().setLayout(JIFLoginLayout);
        JIFLoginLayout.setHorizontalGroup(
            JIFLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFLoginLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(JIFLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblContraseña)
                    .addComponent(lblUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JIFLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngresar)
                    .addGroup(JIFLoginLayout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addGroup(JIFLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCorreo)
                            .addComponent(txtContraseña))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JIFLoginLayout.setVerticalGroup(
            JIFLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JIFLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JIFLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContraseña)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnIngresar)
                .addGap(58, 58, 58))
        );

        desktopPane.add(JIFLogin);
        JIFLogin.setBounds(30, 10, 280, 200);

        JIFListarEmpleados.setClosable(true);
        JIFListarEmpleados.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        JIFListarEmpleados.setIconifiable(true);
        JIFListarEmpleados.setMaximizable(true);
        JIFListarEmpleados.setResizable(true);
        JIFListarEmpleados.setTitle("Listar Trabajadores");
        JIFListarEmpleados.setVisible(false);

        TBLTrabajadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Salario", "Licencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TBLTrabajadores);

        javax.swing.GroupLayout JIFListarEmpleadosLayout = new javax.swing.GroupLayout(JIFListarEmpleados.getContentPane());
        JIFListarEmpleados.getContentPane().setLayout(JIFListarEmpleadosLayout);
        JIFListarEmpleadosLayout.setHorizontalGroup(
            JIFListarEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFListarEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JIFListarEmpleadosLayout.setVerticalGroup(
            JIFListarEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFListarEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desktopPane.add(JIFListarEmpleados);
        JIFListarEmpleados.setBounds(50, 0, 310, 210);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Inicio");

        InoListarTrabadores.setMnemonic('o');
        InoListarTrabadores.setText("Listar Trabajadores");
        InoListarTrabadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InoListarTrabadoresActionPerformed(evt);
            }
        });
        fileMenu.add(InoListarTrabadores);

        InoCrearTrabajador.setMnemonic('s');
        InoCrearTrabajador.setText("Crear Trabajador");
        InoCrearTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InoCrearTrabajadorActionPerformed(evt);
            }
        });
        fileMenu.add(InoCrearTrabajador);

        InoCalcularNomina.setMnemonic('a');
        InoCalcularNomina.setText("CalcularNomina");
        fileMenu.add(InoCalcularNomina);

        InoSalir.setMnemonic('x');
        InoSalir.setText("Salir");
        InoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InoSalirActionPerformed(evt);
            }
        });
        fileMenu.add(InoSalir);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Opcion");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Grafica");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InoSalirActionPerformed
       
        JOptionPane.showMessageDialog(rootPane, "Gracias por mirar la nomina de sus trabadores");
        System.exit(0);
    }//GEN-LAST:event_InoSalirActionPerformed

    private void InoListarTrabadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InoListarTrabadoresActionPerformed
        // TODO add your handling code here:
        if(JIFListarEmpleados.isIcon())
        {
            try {
                JIFListarEmpleados.setIcon(false);
            } catch (PropertyVetoException ex) {
                System.out.println("No se pudo restaurar el formulario listar trabajadores");
            }
        }
        JIFListarEmpleados.show();
        
    }//GEN-LAST:event_InoListarTrabadoresActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        
        
        
        
        if (txtCorreo.getText().equals("") || txtContraseña.getText().equals(""))
        {
        JOptionPane.showMessageDialog(rootPane, "Debe digitar los campos obligatorios", "Error", 0);
        }
        else
        {
            if(controlUsuarios.verificarUsuario(txtCorreo.getText(), txtContraseña.getText()))
                
            {
            controlarEstadoInicio(true);
            JIFLogin.hide();
            }
            else
            {
            JOptionPane.showMessageDialog(rootPane, "Los datos ingresados son errados", "Error", 0);
            }
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void TXTCrearTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCrearTrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCrearTrabajadorActionPerformed

    private void InoCrearTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InoCrearTrabajadorActionPerformed
        // TODO add your handling code here:
        if(JIFRegistrarTrabajador.isIcon())
        {
            try {
                JIFRegistrarTrabajador.setIcon(Boolean.FALSE);
            } catch (PropertyVetoException ex) {
                System.out.println("No se encontraba minimizado");
            }
        }
        JIFRegistrarTrabajador.show();
        
    }//GEN-LAST:event_InoCrearTrabajadorActionPerformed

    private void tbRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbRegistrarActionPerformed

         Trabajador jaime = new TecSistemas("54628", "jaime castro", 2000000, false);
         String mensaje= controlNomina.adicionarTrajador(jaime);
         
          llenarTrabajadores();
         JOptionPane.showMessageDialog(rootPane, mensaje);
    }//GEN-LAST:event_tbRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIINomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIINomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIINomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIINomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIINomina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem InoCalcularNomina;
    private javax.swing.JMenuItem InoCrearTrabajador;
    private javax.swing.JMenuItem InoListarTrabadores;
    private javax.swing.JMenuItem InoSalir;
    private javax.swing.JInternalFrame JIFListarEmpleados;
    private javax.swing.JInternalFrame JIFLogin;
    private javax.swing.JInternalFrame JIFRegistrarTrabajador;
    private javax.swing.JTable TBLTrabajadores;
    private javax.swing.JTextField TXTCrearTrabajador;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JToggleButton tbRegistrar;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables

}
